# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161121_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='venue',
            new_name='Host',
        ),
    ]
