# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161121_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='games',
        ),
        migrations.DeleteModel(
            name='teams',
        ),
    ]
