# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Host', models.TextField()),
                ('teamA', models.TextField()),
                ('teamB', models.TextField()),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('competition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
