# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='game',
        ),
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
