# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161123_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('wonByTeamA', models.IntegerField()),
                ('wonByTeamB', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('teamApoints', models.IntegerField()),
                ('teamBpoints', models.IntegerField()),
            ],
        ),
    ]
