# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_overall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overall',
            old_name='teamApoints',
            new_name='teamAPoints',
        ),
        migrations.RenameField(
            model_name='overall',
            old_name='teamBpoints',
            new_name='teamBPoints',
        ),
        migrations.AddField(
            model_name='overall',
            name='location',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
