# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20161129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall',
            name='teamA',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overall',
            name='teamB',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
