# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20161129_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Host',
            new_name='host',
        ),
    ]
