# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
