# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161124_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, default='media/images', null=True, upload_to='media/images'),
        ),
    ]
